import { Award, BookOpenCheck, CheckCircle2, CreditCard, FileText, Star, UserRound } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { cursoService } from '../Curso/cursoService';
import { planoService } from '../Plano/planoService';
import { alunoService } from './alunoService';

function idOf(item) { return Object.entries(item).find(([key]) => /^ID_[A-Za-z]+$/.test(key))?.[1]; }
function Message({ error, notice }) { return <>{error && <p className="form-error">{error}</p>}{notice && <p className="success-message">{notice}</p>}</>; }

export function MatriculasPage() {
  const [matriculas, setMatriculas] = useState([]); const [cursos, setCursos] = useState([]); const [curso, setCurso] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { const [m, c] = await Promise.all([alunoService.matriculas(), cursoService.listar()]); setMatriculas(m); setCursos(c); }, []);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function submit(e) { e.preventDefault(); try { await alunoService.matricular(curso); setNotice('Matrícula realizada.'); setCurso(''); await load(); } catch (err) { setError(err.message); } }
  const matriculados = new Set(matriculas.map((m) => m.ID_Curso));
  return <section className="page"><header className="page-heading"><div><p className="eyebrow">Minha jornada</p><h1>Meus cursos</h1></div></header><Message error={error} notice={notice}/><form className="panel form-panel inline-form" onSubmit={submit}><label className="field"><span>Matricule-se em um curso</span><select value={curso} onChange={(e) => setCurso(e.target.value)} required><option value="">Selecione</option>{cursos.filter((c) => !matriculados.has(c.ID_Curso)).map((c) => <option key={c.ID_Curso} value={c.ID_Curso}>{c.Titulo}</option>)}</select></label><button className="button primary"><BookOpenCheck size={18}/>Matricular</button></form><div className="panel table-panel"><table><thead><tr><th>Curso</th><th>Nível</th><th>Matrícula</th><th>Conclusão</th></tr></thead><tbody>{matriculas.map((m) => <tr key={m.ID_Matricula}><td>{m.Curso.Titulo}</td><td>{m.Curso.Nivel}</td><td>{new Date(m.DataMatricula).toLocaleDateString('pt-BR')}</td><td>{m.DataConclusao ? new Date(m.DataConclusao).toLocaleDateString('pt-BR') : 'Em andamento'}</td></tr>)}</tbody></table></div></section>;
}

export function ProgressoPage() {
  const [items, setItems] = useState([]); const [error, setError] = useState('');
  const load = useCallback(() => alunoService.progresso().then(setItems).catch((e) => setError(e.message)), []); useEffect(() => { load(); }, [load]);
  async function toggle(item) { try { await alunoService.marcarProgresso(item.ID_Aula, item.Status === 'Concluida' ? 'Em andamento' : 'Concluida'); load(); } catch (e) { setError(e.message); } }
  return <section className="page"><header className="page-heading"><div><p className="eyebrow">Minha jornada</p><h1>Progresso das aulas</h1></div></header><Message error={error}/><div className="panel table-panel"><table><thead><tr><th>Curso</th><th>Módulo</th><th>Aula</th><th>Status</th><th>Ação</th></tr></thead><tbody>{items.map((item) => <tr key={item.ID_Aula}><td>{item.Curso}</td><td>{item.Modulo}</td><td>{item.Aula}</td><td>{item.Status}</td><td><button className="button secondary" onClick={() => toggle(item)}>{item.Status === 'Concluida' ? 'Marcar pendente' : 'Marcar vista'}</button></td></tr>)}</tbody></table></div></section>;
}

export function AvaliacoesPage() {
  const [items, setItems] = useState([]); const [matriculas, setMatriculas] = useState([]); const [form, setForm] = useState({ ID_Curso: '', Nota: '', Comentario: '' }); const [error, setError] = useState('');
  const load = useCallback(async () => { const [a, m] = await Promise.all([alunoService.avaliacoes(), alunoService.matriculas()]); setItems(a); setMatriculas(m.filter((x) => x.DataConclusao)); }, []); useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function submit(e) { e.preventDefault(); try { await alunoService.avaliar(form); setForm({ ID_Curso: '', Nota: '', Comentario: '' }); await load(); } catch (err) { setError(err.message); } }
  return <section className="page"><header className="page-heading"><div><p className="eyebrow">Minha jornada</p><h1>Avaliações</h1></div></header><Message error={error}/><form className="panel form-panel inline-form" onSubmit={submit}><label className="field"><span>Curso concluído</span><select value={form.ID_Curso} onChange={(e) => setForm({...form, ID_Curso:e.target.value})} required><option value="">Selecione</option>{matriculas.map((m) => <option key={m.ID_Curso} value={m.ID_Curso}>{m.Curso.Titulo}</option>)}</select></label><label className="field"><span>Nota</span><input type="number" min="1" max="5" value={form.Nota} onChange={(e) => setForm({...form, Nota:e.target.value})} required/></label><label className="field"><span>Comentário</span><input value={form.Comentario} onChange={(e) => setForm({...form, Comentario:e.target.value})}/></label><button className="button primary"><Star size={18}/>Avaliar</button></form><div className="panel table-panel"><table><thead><tr><th>Curso</th><th>Nota</th><th>Comentário</th><th>Data</th></tr></thead><tbody>{items.map((a) => <tr key={a.ID_Avaliacao}><td>{a.Curso.Titulo}</td><td>{a.Nota}</td><td>{a.Comentario || '-'}</td><td>{new Date(a.DataAvaliacao).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></section>;
}

export function CertificadosPage() {
  const [items, setItems] = useState([]); const [matriculas, setMatriculas] = useState([]); const [curso, setCurso] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { const [c, m] = await Promise.all([alunoService.certificados(), alunoService.matriculas()]); setItems(c); setMatriculas(m.filter((x) => x.DataConclusao)); }, []); useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function submit(e) { e.preventDefault(); try { await alunoService.obterCertificado(curso); setCurso(''); await load(); } catch (err) { setError(err.message); } }
  const emitidos = new Set(items.map((item) => item.ID_Curso));
  return <section className="page"><header className="page-heading"><div><p className="eyebrow">Minha jornada</p><h1>Certificados</h1></div></header><Message error={error}/><form className="panel form-panel inline-form" onSubmit={submit}><label className="field"><span>Curso concluído</span><select value={curso} onChange={(e) => setCurso(e.target.value)} required><option value="">Selecione</option>{matriculas.filter((m) => !emitidos.has(m.ID_Curso)).map((m) => <option key={m.ID_Curso} value={m.ID_Curso}>{m.Curso.Titulo}</option>)}</select></label><button className="button primary"><Award size={18}/>Obter certificado</button></form><div className="panel table-panel"><table><thead><tr><th>Curso</th><th>Código de verificação</th><th>Emissão</th></tr></thead><tbody>{items.map((item) => <tr key={item.ID_Certificado}><td>{item.Curso.Titulo}</td><td>{item.CodigoVerificacao}</td><td>{new Date(item.DataEmissao).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></section>;
}

export function AssinaturasPage() {
  const [items, setItems] = useState([]); const [planos, setPlanos] = useState([]); const [plano, setPlano] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { const [a, p] = await Promise.all([alunoService.assinaturas(), planoService.listar()]); setItems(a); setPlanos(p); }, []); useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function submit(e) { e.preventDefault(); try { await alunoService.assinar(plano); setPlano(''); await load(); } catch (err) { setError(err.message); } }
  return <section className="page"><header className="page-heading"><div><p className="eyebrow">Minha conta</p><h1>Assinaturas</h1></div></header><Message error={error}/><form className="panel form-panel inline-form" onSubmit={submit}><label className="field"><span>Plano</span><select value={plano} onChange={(e) => setPlano(e.target.value)} required><option value="">Selecione</option>{planos.map((p) => <option key={p.ID_Plano} value={p.ID_Plano}>{p.Nome} — R$ {p.Preco}</option>)}</select></label><button className="button primary"><CreditCard size={18}/>Assinar</button></form><div className="panel table-panel"><table><thead><tr><th>Plano</th><th>Valor</th><th>Início</th><th>Término</th></tr></thead><tbody>{items.map((item) => <tr key={item.ID_Assinatura}><td>{item.Plano.Nome}</td><td>R$ {item.Plano.Preco}</td><td>{new Date(item.DataInicio).toLocaleDateString('pt-BR')}</td><td>{new Date(item.DataFim).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></section>;
}

export function PagamentosPage() {
  const [items, setItems] = useState([]); const [assinaturas, setAssinaturas] = useState([]); const [form, setForm] = useState({ ID_Assinatura: '', ValorPago: '', MetodoPagamento: 'Pix', Id_Transacao_Gateway: '' }); const [error, setError] = useState('');
  const load = useCallback(async () => { const [p, a] = await Promise.all([alunoService.pagamentos(), alunoService.assinaturas()]); setItems(p); setAssinaturas(a); }, []); useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function submit(e) { e.preventDefault(); try { await alunoService.pagar(form); setForm({ ID_Assinatura: '', ValorPago: '', MetodoPagamento: 'Pix', Id_Transacao_Gateway: '' }); await load(); } catch (err) { setError(err.message); } }
  return <section className="page"><header className="page-heading"><div><p className="eyebrow">Minha conta</p><h1>Pagamentos</h1></div></header><Message error={error}/><form className="panel form-panel inline-form" onSubmit={submit}><label className="field"><span>Assinatura</span><select value={form.ID_Assinatura} onChange={(e) => setForm({...form, ID_Assinatura:e.target.value})} required><option value="">Selecione</option>{assinaturas.map((a) => <option key={a.ID_Assinatura} value={a.ID_Assinatura}>{a.Plano.Nome}</option>)}</select></label><label className="field"><span>Valor pago</span><input type="number" min="0" step=".01" value={form.ValorPago} onChange={(e) => setForm({...form, ValorPago:e.target.value})} required/></label><label className="field"><span>Método</span><select value={form.MetodoPagamento} onChange={(e) => setForm({...form, MetodoPagamento:e.target.value})}><option>Pix</option><option>Cartao de credito</option><option>Boleto</option></select></label><label className="field"><span>ID da transação</span><input value={form.Id_Transacao_Gateway} onChange={(e) => setForm({...form, Id_Transacao_Gateway:e.target.value})} required/></label><button className="button primary"><CreditCard size={18}/>Registrar pagamento</button></form><div className="panel table-panel"><table><thead><tr><th>Plano</th><th>Valor</th><th>Método</th><th>Data</th></tr></thead><tbody>{items.map((item) => <tr key={item.ID_Pagamento}><td>{item.Assinatura.Plano.Nome}</td><td>R$ {item.ValorPago}</td><td>{item.MetodoPagamento}</td><td>{new Date(item.DataPagamento).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></section>;
}

export function ContaPage() {
  const [form, setForm] = useState({}); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { alunoService.conta().then((item) => setForm({ NomeCompleto: item.NomeCompleto, Email: item.Email, Senha: '' })).catch((e) => setError(e.message)); }, []);
  async function submit(e) { e.preventDefault(); try { const data = { NomeCompleto: form.NomeCompleto }; if (form.Senha) data.Senha = form.Senha; await alunoService.atualizarConta(data); setForm({...form, Senha: ''}); setNotice('Conta atualizada.'); } catch (err) { setError(err.message); } }
  return <section className="page narrow-page"><header className="page-heading"><div><p className="eyebrow">Minha conta</p><h1>Dados pessoais</h1></div></header><Message error={error} notice={notice}/><form className="panel form-panel" onSubmit={submit}><div className="form-grid"><label className="field"><span>Nome completo</span><input value={form.NomeCompleto || ''} onChange={(e) => setForm({...form, NomeCompleto:e.target.value})} required/></label><label className="field"><span>E-mail</span><input value={form.Email || ''} disabled/></label><label className="field"><span>Nova senha</span><input type="password" minLength="6" value={form.Senha || ''} onChange={(e) => setForm({...form, Senha:e.target.value})}/></label></div><div className="form-actions"><button className="button primary"><UserRound size={18}/>Salvar dados</button></div></form></section>;
}
